### ISSUE TITLE
CollectD plugin throws segfault when configuration is missing

### ISSUE THREAD

**Issue by matthayter** [ArpNetworking/metrics#12]
##

**Comment by vjkoskela** [comment]
@matthayter Do you have someone on your end that wants to take a look at this? From our perspective this is not a high priority as we are working to integrate CollectD via HTTP instead. However, I can see if this is something that causes problems for you that a patch may be warranted here even if it is not going to be used in the long term (and that's assuming you are migrating your setup to HTTP as well).

**Comment by matthayter** [comment]
The team here that was going to use it ended up writing their own plugin in python, so nope, not high-pri here either. Closing this is not unreasonable IMO.

**Comment by vjkoskela** [comment]
Collectd file plugin is no longer supported; for alternatives please see #13. Resolving.
