### ISSUE TITLE
CollectD plugin not portable across CollectD versions

### ISSUE THREAD

**Issue by fr0stbyte** [ArpNetworking/metrics#13]
- developing the plugin in C definitely has a performance advantage, as well as, perhaps access to internal data structures of CollectD that may not be exposed otherwise.
- however, patching the collectd source means that it needs to be patched at every collectd release, especially if one is to use the distro's provided collectd
- we tried using .so lib compiled for 5.4.1 with 5.5.1 and it caused a SIGSEGV
- if performance is not a concern, perhaps using something like python/perl plugin, would be preferable and more portable across CollectD versions

**Comment by vjkoskela** [comment]
So just to be clear our plugin is not a patch to CollectD source code. The plugin's source code is entirely independent of the rest of the CollectD source. You do have to register the plugin with the build system which can be a little daunting at first. However, we had continuous build setup for this at Groupon and it worked very well with almost no maintenance.

It is not surprising that the compiled plugin does not work across 5.4.1 and 5.5.1. However, you _should_ be able to simply recompile the plugin after upgrading the version of CollectD it is compiled against and be good to go. There is always a small chance that a Y change contains some semantic difference that can output the correctness of the recorded data.

I am a little surprised that it caused a SIGSEV. Do you have a stack dump you can post?

We will gladly accept a pull request for an alternate CollectD integration point. However, our plans are to move to the CollectD HTTP plugin and remove the intermediate file altogether. So we have no plans to develop an alternative file based integration or to upgrade the existing one past version 2C.

**Comment by vjkoskela** [comment]
MAD supports the Collectd HTTP source and the file output plugin is now deprecated. You can find example configuration of the Collectd HTTP source here:

https://github.com/ArpNetworking/metrics-aggregator-daemon/blob/master/config/pipelines/pipeline.conf#L85

We also support a Telegraf input source as well. Example:

https://github.com/ArpNetworking/metrics-aggregator-daemon/blob/master/config/pipelines/pipeline.conf#L67
