### ISSUE TITLE
start.sh "find_path_up" returns root instead of emitting an error message

### ISSUE THREAD

**Issue by wittekm** [ArpNetworking/metrics#27]
In build/start.sh, we do the following logic:

```
dir_mad=`find_path_up metrics-aggregator-daemon`

if [ "${start_mad}" -gt 0 ] && [ ! -d "${dir_mad}" ]; then
  echo "No directory found for requested project mad"
  exit 1
fi
```

As it turns out, `find_path_up` returns the root `/` if it can't find such a sibling directory.

This makes the  `[! -d "${dir_mad}"]` check - that is to say, the `[not folder-exists /]` - always evaluate to false, meaning we'll never fall into any of these 3 if statements.

**Comment by vjkoskela** [comment]
Including in my next PR.
