### ISSUE TITLE
Problem while downloading : invalid sha1 

### ISSUE THREAD

**Issue by maclaze** [ArpNetworking/metrics#8]
problem while downloading module descriptor: https://repo1.maven.org/maven2/com/arpnetworking/build/arpnetworking-parent-pom/1.0.1/arpnetworking-parent-pom-1.0.1.pom: invalid sha1: expected=a5953353749f0e5e72a6b5f83f07ccb9b221007f computed=cd8aa957ff3d960ceebe9e4687cc051ce6a9d1be

**Comment by BrandonArp** [comment]
Can you give me a bit more information? Which project were you trying to build when this happened?

**Comment by BrandonArp** [comment]
Likely this is a problem with the download.  Can you try deleting the pom out of your maven cache and try running the build again?

**Comment by maclaze** [comment]
@BrandonArp Will try it and update you.

**Comment by BrandonArp** [comment]
The pom in central was corrupt.  We've since moved to a newer one anyway.
